# docker-compose.production.yml
version: '3'

volumes:
  pg_data_kitty_production:
  static_kitty_production:
  media_kitty_production:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  backend:
    image: tetkaslepoka/kittygram_backend
    env_file: .env
    volumes:
      - static_kittygram:/backend_static/
      - media_kittygram:/app/media/cats/images/
    depends_on:
    - db
  frontend:
    image: tetkaslepoka/kittygram_frontend  # Качаем с DockerHub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kittygram:/frontend_static
  gateway:
    image: tetkaslepoka/kittygram_gateway  # Качаем с DockerHub
    # env_file: .env
    volumes:
      - static_kittygram:/staticfiles/
      - media_kittygram:/media/cats/images/
    ports:
      - 9000:80
    depends_on:
      - backend